# Generated by Django 4.1.1 on 2022-09-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_musicion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musicion',
            table='musiction',
        ),
    ]
