# Generated by Django 4.1.1 on 2022-09-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='autuor',
            new_name='author',
        ),
    ]
